version: '3.3'

services:
  web:
    image: venkateshbr/inventory:0.1
    ports:
    - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres@123
    depends_on:
    - postgres
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment: 
      - POSTGRES_DB=inventory
      - POSTGRES_PASSWORD=postgres@123
